language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
before_install:
- pip install --user awscli
- pip install --user s3cmd
- npm install -g npm@5
- npm install -g greenkeeper-lockfile@1
install:
  - npm install
  - npm prune
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run lint
  - make test
after_success:
  - npm run semantic-release
  - make update
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
matrix:
  include:
    - node_js: '6'
    - node_js: 'node'
